### ISSUE TITLE
tasks are not displayed

### ISSUE THREAD

**Issue by valdomagana** [Orangescrum/orangescrum#19]
![image](https://user-images.githubusercontent.com/99688841/195201080-372b07e9-9d39-4517-ac91-6a5490981409.png)

**Comment by Andolatapan** [comment]
**@valdomagana** please share 1) Error log file inside (app/tmp/logs) & 2) Browser console error

**Comment by valdomagana** [comment]
[error.log](https://github.com/Orangescrum/orangescrum/files/9766752/error.log)

![image](https://user-images.githubusercontent.com/99688841/195393837-9eab2587-100e-4bff-9160-a192e28a320a.png)

**Comment by Andolatapan** [comment]
@valdomagana thank you for sharing the files. The issue is with the loading template. 
Please clear your browser cache & local storage and refresh the page. 
Let me know.

**Comment by ubaid541** [comment]
Hi, I am facing the same issue with the loading screen. I tried to clear local storage but the screen task screen is still loading.

Note: I have installed open source version from cpanel.

**Comment by Andolatapan** [comment]
@ubaid541 please download the recent version of open source and try to install it. Recently we fixed a few issues.
Let me know if this works for you.

**Comment by valdomagana** [comment]
Hello, thank you very much for the help, but the problem continues, I deleted cache memory, browser and updated the version and the same problem continues. :(

![image](https://user-images.githubusercontent.com/99688841/196488696-6e989d2f-6a96-4785-b478-9cfa9282c6ca.png)
[error (2).log](https://github.com/Orangescrum/orangescrum/files/9812716/error.2.log)

**Comment by ubaid541** [comment]
@Andolatapan thanks for your reply. But the problem is still there. Even I tried to install a fresh open-source copy from GitHub. Kindly can you guide me? Thanks

**Comment by akguptach** [comment]
same issue i am getting

**Comment by digitalcuritiba** [comment]
Solution?

**Comment by SmoothMC** [comment]
Same issue here...please help...

**Comment by Anil-Chaudhary-netclues** [comment]
Please check try with Dedicated server if you are using shared server then it will be the issue on shared server. we have done with Dedicated server.

**Comment by febriarief** [comment]
same issue. 
but in my case, i forgot to install mbstring extension.
after install and enable it in php.ini, it works!

tested on:
- ubuntu 18.04
- php 7.4
- mysql 5.7
